# Generated by Django 5.2.8 on 2025-11-19 03:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Short label, e.g. 'Check tires'", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional longer description / instructions",
                    ),
                ),
                (
                    "machine_type",
                    models.CharField(
                        blank=True,
                        help_text="Optional machine type filter, e.g. 'Excavator'. Leave blank for all.",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordering in the checklist"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="JobSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Project / Job site name", max_length=100
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Internal code, e.g. SITE-001 or PROJ-MEX-23",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Optional address or location description",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Internal ID, e.g. EXC-001",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name, e.g. Excavadora CAT 320D",
                        max_length=100,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, help_text="Excavator, Loader, etc.", max_length=50
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=50)),
                ("model", models.CharField(blank=True, max_length=50)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "qr_slug",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID used for QR links",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_USE", "In use"),
                            ("MAINTENANCE", "Under maintenance"),
                            ("OUT_OF_SERVICE", "Out of service"),
                            ("TRANSIT", "In transit"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="UsageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator_name",
                    models.CharField(
                        help_text="Name of the operator for this session",
                        max_length=100,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        help_text="When the operator used the machine"
                    ),
                ),
                (
                    "engine_hours_start",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hour meter before use",
                        max_digits=8,
                    ),
                ),
                (
                    "engine_hours_end",
                    models.DecimalField(
                        decimal_places=2, help_text="Hour meter after use", max_digits=8
                    ),
                ),
                (
                    "fuel_level_start",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Fuel level (%) at start", null=True
                    ),
                ),
                (
                    "fuel_level_end",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Fuel level (%) at end", null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude of the machine when report was created",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude of the machine when report was created",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project / job site where the machine was used",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_reports",
                        to="fleet.jobsite",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_reports",
                        to="fleet.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsagePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("FRONT", "Front"),
                            ("BACK", "Back"),
                            ("LEFT", "Left side"),
                            ("RIGHT", "Right side"),
                            ("WHEELS", "Wheels / Tracks"),
                            ("COCKPIT", "Cockpit / Controls"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="usage_photos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usage_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="fleet.usagereport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChecklistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("ISSUE", "Issue"),
                            ("NA", "Not applicable"),
                        ],
                        default="OK",
                        max_length=10,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional notes if there is an issue"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="fleet.checklistitem",
                    ),
                ),
                (
                    "usage_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_entries",
                        to="fleet.usagereport",
                    ),
                ),
            ],
            options={
                "unique_together": {("usage_report", "item")},
            },
        ),
    ]
