# Generated by Django 5.2.8 on 2025-11-19 20:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagereport",
            name="administrator_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the administrator receiving the machine",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="usagereport",
            name="administrator_signature",
            field=models.ImageField(
                blank=True,
                help_text="Administrator signature",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="signatures/",
            ),
        ),
        migrations.AddField(
            model_name="usagereport",
            name="operator_signature",
            field=models.ImageField(
                blank=True,
                help_text="Operator signature",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="signatures/",
            ),
        ),
        migrations.AlterField(
            model_name="usagephoto",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="usage_photos/",
            ),
        ),
    ]
