# Generated by Django 5.2.8 on 2025-11-21 17:09

from django.db import migrations, models


def migrate_engine_hours_data(apps, schema_editor):
    """Copy engine_hours_end to engine_hours for existing records."""
    UsageReport = apps.get_model("fleet", "UsageReport")
    for report in UsageReport.objects.all():
        if report.engine_hours_end is not None:
            report.engine_hours = report.engine_hours_end
            report.save(update_fields=["engine_hours"])


def migrate_checklist_values(apps, schema_editor):
    """Convert old OK values to NO_ISSUE."""
    ChecklistEntry = apps.get_model("fleet", "ChecklistEntry")
    ChecklistEntry.objects.filter(value="OK").update(value="NO_ISSUE")


def reverse_checklist_values(apps, schema_editor):
    """Convert NO_ISSUE back to OK for reverse migration."""
    ChecklistEntry = apps.get_model("fleet", "ChecklistEntry")
    ChecklistEntry.objects.filter(value="NO_ISSUE").update(value="OK")


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_add_signatures"),
    ]

    operations = [
        # Step 1: Add new engine_hours field (nullable)
        migrations.AddField(
            model_name="usagereport",
            name="engine_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Current hour meter reading at time of report",
                max_digits=8,
                null=True,
            ),
        ),
        # Step 2: Migrate data from engine_hours_end to engine_hours
        migrations.RunPython(migrate_engine_hours_data, migrations.RunPython.noop),
        # Step 3: Remove old fields
        migrations.RemoveField(
            model_name="usagereport",
            name="engine_hours_end",
        ),
        migrations.RemoveField(
            model_name="usagereport",
            name="engine_hours_start",
        ),
        # Step 4: Make engine_hours required (remove null=True)
        migrations.AlterField(
            model_name="usagereport",
            name="engine_hours",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Current hour meter reading at time of report",
                max_digits=8,
            ),
        ),
        # Step 5: Update checklist entry values
        migrations.RunPython(migrate_checklist_values, reverse_checklist_values),
        # Step 6: Update checklist field choices
        migrations.AlterField(
            model_name="checklistentry",
            name="value",
            field=models.CharField(
                choices=[
                    ("ISSUE", "There is an issue"),
                    ("NO_ISSUE", "No issue"),
                    ("NA", "N/A"),
                ],
                default="NO_ISSUE",
                max_length=10,
            ),
        ),
    ]
