# Generated by Django 5.2.8 on 2026-03-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0003_update_engine_hours_and_checklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("YES_NO", "Sí / No"),
                    ("CONDITION", "Buen estado / Mal estado"),
                    ("FUEL", "Nivel de combustible (Bajo / Medio / Lleno)"),
                    ("EXTINTOR", "Extintor (Hay / No hay)"),
                ],
                default="YES_NO",
                help_text="Determines which answer options are shown to the operator",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="notification_emails",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated email addresses to notify when a report is submitted, e.g. manager@macnova.com,supervisor@macnova.com",
            ),
        ),
        migrations.AlterField(
            model_name="checklistentry",
            name="value",
            field=models.CharField(
                choices=[
                    ("SI", "Sí"),
                    ("NO", "No"),
                    ("BUEN_ESTADO", "Buen estado"),
                    ("MAL_ESTADO", "Mal estado"),
                    ("BAJO", "Bajo"),
                    ("MEDIO", "Medio"),
                    ("LLENO", "Lleno"),
                    ("HAY", "Hay"),
                    ("NO_HAY", "No hay"),
                    ("ISSUE", "Hay un problema"),
                    ("NO_ISSUE", "Sin problema"),
                    ("NA", "N/A"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="description",
            field=models.TextField(blank=True, help_text="Optional longer description"),
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order in the checklist"
            ),
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="label",
            field=models.CharField(
                help_text="Short label, e.g. 'Fuga de aceite'", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="machine_type",
            field=models.CharField(
                blank=True,
                help_text="Optional machine type filter. Leave blank for all.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="usagephoto",
            name="image",
            field=models.ImageField(upload_to="usage_photos/"),
        ),
        migrations.AlterField(
            model_name="usagephoto",
            name="photo_type",
            field=models.CharField(
                choices=[
                    ("PLACA", "Placa / Identificación"),
                    ("FRONT", "Frente"),
                    ("BACK", "Atrás"),
                    ("LEFT", "Lado izquierdo"),
                    ("RIGHT", "Lado derecho"),
                    ("WHEELS", "Orugas / Neumáticos"),
                    ("COCKPIT", "Cabina"),
                    ("ENGINE", "Motor"),
                    ("METER", "Horómetro"),
                    ("OTHER", "Otra"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usagereport",
            name="administrator_signature",
            field=models.ImageField(blank=True, null=True, upload_to="signatures/"),
        ),
        migrations.AlterField(
            model_name="usagereport",
            name="date",
            field=models.DateTimeField(
                db_index=True, help_text="When the operator used the machine"
            ),
        ),
        migrations.AlterField(
            model_name="usagereport",
            name="engine_hours",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Current hour meter reading at time of report (end reading)",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="usagereport",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usagereport",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usagereport",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usage_reports",
                to="fleet.machine",
            ),
        ),
        migrations.AlterField(
            model_name="usagereport",
            name="operator_signature",
            field=models.ImageField(blank=True, null=True, upload_to="signatures/"),
        ),
    ]
